version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X srun/internal/version.Version={{.Version}}
      - -X srun/internal/version.GitCommit={{.Commit}}
      - -X srun/internal/version.BuildDate={{.Date}}
    main: ./cmd/srun

archives:
  - formats: ["tar.gz"]
    files:
      - none*
    name_template: "{{ tolower .ProjectName }}_{{ tolower .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch
